spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      "[hibernate.format_sql]": false

  devtools:
    restart:
      enabled: false

server:
  port: 0

app:
  seed:
    size: ${APP_SEED_SIZE:50}
    category-count: ${APP_SEED_CATEGORY_COUNT:12}
    default-password: ${APP_SEED_DEFAULT_PASSWORD:}

logging:
  level:
    org.hibernate.SQL: warn
