package com.bookstore.bookstore.domain.enums;

public enum PermissionCode {
    BOOK_VIEW,
    BOOK_CREATE,
    BOOK_UPDATE,
    BOOK_DELETE,

    CATEGORY_VIEW,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    AUTHOR_VIEW,
    AUTHOR_CREATE,
    AUTHOR_UPDATE,
    AUTHOR_DELETE,

    PUBLISHER_VIEW,
    PUBLISHER_CREATE,
    PUBLISHER_UPDATE,
    PUBLISHER_DELETE,

    ORDER_CREATE,
    ORDER_VIEW_OWN,
    ORDER_VIEW_ALL,
    ORDER_UPDATE_STATUS,
    ORDER_CANCEL_OWN,

    USER_VIEW,
    USER_MANAGE,

    ROLE_VIEW,
    ROLE_MANAGE,

    REVIEW_CREATE,
    REVIEW_MANAGE,

    COUPON_MANAGE,
    DASHBOARD_VIEW
}
