package com.bookstore.bookstore.domain.exception;

public enum DomainErrorCode {

    INVALID_USER_ID("DOMAIN_USER_001", "%s khong duoc null"),
    INVALID_USER_USERNAME("DOMAIN_USER_002", "%s khong duoc de trong"),
    INVALID_USER_PASSWORD_HASH("DOMAIN_USER_003", "%s khong duoc de trong"),
    INVALID_USER_PHONE_NUMBER("DOMAIN_USER_004", "%s phai co dung 10 chu so va bat dau bang 0"),
    INVALID_USER_EMAIL("DOMAIN_USER_005", "%s phai ket thuc bang @gmail.com"),
    INVALID_USER_STATUS("DOMAIN_USER_006", "%s khong duoc null"),
    INVALID_USER_ROLES("DOMAIN_USER_007", "%s khong duoc chua phan tu null"),
    INVALID_USER_CREATED_AT("DOMAIN_USER_008", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_UPDATED_AT("DOMAIN_USER_009", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_DELETED_AT("DOMAIN_USER_010", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_AUDIT_ORDER("DOMAIN_USER_011", "%s khong duoc som hon %s"),
    USER_ALREADY_EXISTS("DOMAIN_USER_012", "user da ton tai"),
    USER_NOT_FOUND("DOMAIN_USER_013", "khong tim thay user"),
    USER_USERNAME_ALREADY_EXISTS("DOMAIN_USER_014", "username da ton tai"),
    USER_ALREADY_ACTIVE("DOMAIN_USER_015", "user da duoc kich hoat"),
    BLOCKED_USER_CANNOT_BE_ACTIVATED("DOMAIN_USER_016", "tai khoan bi khoa khong the kich hoat"),
    DELETED_USER_CANNOT_BE_ACTIVATED("DOMAIN_USER_017", "tai khoan da xoa khong the kich hoat"),
    USER_ALREADY_DELETED("DOMAIN_USER_018", "user da bi xoa"),
    USER_NOT_ACTIVE_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_019", "tai khoan khong hoat dong khong the cap nhat thong tin"),
    BLOCKED_USER_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_020", "tai khoan bi khoa khong the cap nhat thong tin"),
    DELETED_USER_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_021", "tai khoan da xoa khong the cap nhat thong tin"),
    USER_PHONE_ALREADY_EXISTS("DOMAIN_USER_022", "phoneNumber da ton tai"),
    USER_EMAIL_ALREADY_EXISTS("DOMAIN_USER_023", "email da ton tai"),
    USER_NOT_ACTIVE_CANNOT_LOGIN("DOMAIN_USER_024", "tai khoan khong hoat dong khong the dang nhap"),
    BLOCKED_USER_CANNOT_LOGIN("DOMAIN_USER_025", "tai khoan bi khoa khong the dang nhap"),
    DELETED_USER_CANNOT_LOGIN("DOMAIN_USER_026", "tai khoan da xoa khong the dang nhap"),

    INVALID_PROFILE_ID("DOMAIN_PROFILE_001", "%s khong duoc null"),
    INVALID_PROFILE_USER_ID("DOMAIN_PROFILE_002", "%s khong duoc null"),
    INVALID_PROFILE_LAST_NAME("DOMAIN_PROFILE_003", "%s khong duoc de trong"),
    INVALID_PROFILE_FIRST_NAME("DOMAIN_PROFILE_004", "%s khong duoc de trong"),
    INVALID_PROFILE_AVATAR_URL("DOMAIN_PROFILE_005", "%s khong duoc de trong"),
    INVALID_PROFILE_GENDER("DOMAIN_PROFILE_006", "%s khong duoc null"),
    INVALID_PROFILE_DATE_OF_BIRTH("DOMAIN_PROFILE_007", "%s khong duoc nam trong tuong lai"),
    INVALID_PROFILE_CREATED_AT("DOMAIN_PROFILE_008", "%s khong duoc nam trong tuong lai"),
    INVALID_PROFILE_UPDATED_AT("DOMAIN_PROFILE_009", "%s khong duoc nam trong tuong lai"),
    INVALID_PROFILE_DELETED_AT("DOMAIN_PROFILE_010", "%s khong duoc nam trong tuong lai"),
    INVALID_PROFILE_AUDIT_ORDER("DOMAIN_PROFILE_011", "%s khong duoc som hon %s"),
    PROFILE_ALREADY_EXISTS("DOMAIN_PROFILE_012", "profile da ton tai"),
    PROFILE_NOT_FOUND("DOMAIN_PROFILE_013", "khong tim thay profile"),
    PROFILE_USER_NOT_FOUND("DOMAIN_PROFILE_014", "khong tim thay user"),
    PROFILE_USER_ALREADY_HAS_PROFILE("DOMAIN_PROFILE_015", "user da co profile"),
    PROFILE_ALREADY_DELETED("DOMAIN_PROFILE_016", "profile da bi xoa"),
    DELETED_PROFILE_CANNOT_UPDATE_PROFILE_INFO("DOMAIN_PROFILE_017", "profile da xoa khong the cap nhat thong tin"),

    INVALID_USER_ADDRESS_ID("DOMAIN_USER_ADDRESS_001", "%s khong duoc null"),
    INVALID_USER_ADDRESS_USER_ID("DOMAIN_USER_ADDRESS_002", "%s khong duoc null"),
    INVALID_USER_ADDRESS_RECEIVER_NAME("DOMAIN_USER_ADDRESS_003", "%s khong duoc de trong"),
    INVALID_USER_ADDRESS_RECEIVER_PHONE("DOMAIN_USER_ADDRESS_004", "%s phai co dung 10 chu so va bat dau bang 0"),
    INVALID_USER_ADDRESS_RECEIVER_ADDRESS("DOMAIN_USER_ADDRESS_005", "%s khong duoc de trong"),
    INVALID_USER_ADDRESS_CREATED_AT("DOMAIN_USER_ADDRESS_006", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_ADDRESS_UPDATED_AT("DOMAIN_USER_ADDRESS_007", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_ADDRESS_DELETED_AT("DOMAIN_USER_ADDRESS_008", "%s khong duoc nam trong tuong lai"),
    INVALID_USER_ADDRESS_AUDIT_ORDER("DOMAIN_USER_ADDRESS_009", "%s khong duoc som hon %s"),
    USER_ADDRESS_ALREADY_DELETED("DOMAIN_USER_ADDRESS_010", "dia chi nhan hang da bi xoa"),
    DELETED_USER_ADDRESS_CANNOT_UPDATE("DOMAIN_USER_ADDRESS_011", "dia chi nhan hang da xoa khong the cap nhat"),
    DELETED_USER_ADDRESS_CANNOT_SET_DEFAULT("DOMAIN_USER_ADDRESS_012", "dia chi nhan hang da xoa khong the dat mac dinh"),

    INVALID_CATEGORY_ID("DOMAIN_CATEGORY_001", "%s khong duoc null"),
    INVALID_CATEGORY_NAME("DOMAIN_CATEGORY_002", "%s khong duoc de trong"),
    INVALID_CATEGORY_CREATED_AT("DOMAIN_CATEGORY_003", "%s khong duoc nam trong tuong lai"),
    INVALID_CATEGORY_UPDATED_AT("DOMAIN_CATEGORY_004", "%s khong duoc nam trong tuong lai"),
    INVALID_CATEGORY_DELETED_AT("DOMAIN_CATEGORY_005", "%s khong duoc nam trong tuong lai"),
    INVALID_CATEGORY_AUDIT_ORDER("DOMAIN_CATEGORY_006", "%s khong duoc som hon %s"),
    CATEGORY_ALREADY_DELETED("DOMAIN_CATEGORY_007", "category da bi xoa"),
    CATEGORY_DATA_NOT_CHANGED("DOMAIN_CATEGORY_008", "du lieu category phai khac du lieu hien tai"),

    INVALID_AUTHOR_ID("DOMAIN_AUTHOR_001", "%s khong duoc null"),
    INVALID_AUTHOR_NAME("DOMAIN_AUTHOR_002", "%s khong duoc de trong"),
    INVALID_AUTHOR_CREATED_AT("DOMAIN_AUTHOR_003", "%s khong duoc nam trong tuong lai"),
    INVALID_AUTHOR_UPDATED_AT("DOMAIN_AUTHOR_004", "%s khong duoc nam trong tuong lai"),
    INVALID_AUTHOR_DELETED_AT("DOMAIN_AUTHOR_005", "%s khong duoc nam trong tuong lai"),
    INVALID_AUTHOR_AUDIT_ORDER("DOMAIN_AUTHOR_006", "%s khong duoc som hon %s"),
    AUTHOR_ALREADY_DELETED("DOMAIN_AUTHOR_007", "author da bi xoa"),
    AUTHOR_DATA_NOT_CHANGED("DOMAIN_AUTHOR_008", "du lieu author phai khac du lieu hien tai"),

    INVALID_PUBLISHER_ID("DOMAIN_PUBLISHER_001", "%s khong duoc null"),
    INVALID_PUBLISHER_NAME("DOMAIN_PUBLISHER_002", "%s khong duoc de trong"),
    INVALID_PUBLISHER_CREATED_AT("DOMAIN_PUBLISHER_003", "%s khong duoc nam trong tuong lai"),
    INVALID_PUBLISHER_UPDATED_AT("DOMAIN_PUBLISHER_004", "%s khong duoc nam trong tuong lai"),
    INVALID_PUBLISHER_DELETED_AT("DOMAIN_PUBLISHER_005", "%s khong duoc nam trong tuong lai"),
    INVALID_PUBLISHER_AUDIT_ORDER("DOMAIN_PUBLISHER_006", "%s khong duoc som hon %s"),
    PUBLISHER_ALREADY_DELETED("DOMAIN_PUBLISHER_007", "publisher da bi xoa"),
    PUBLISHER_DATA_NOT_CHANGED("DOMAIN_PUBLISHER_008", "du lieu publisher phai khac du lieu hien tai"),

    INVALID_SUPPLIER_ID("DOMAIN_SUPPLIER_001", "%s khong duoc null"),
    INVALID_SUPPLIER_NAME("DOMAIN_SUPPLIER_002", "%s khong duoc de trong"),
    INVALID_SUPPLIER_PHONE("DOMAIN_SUPPLIER_003", "%s phai co dung 10 chu so va bat dau bang 0"),
    INVALID_SUPPLIER_EMAIL("DOMAIN_SUPPLIER_004", "%s khong dung dinh dang email"),
    INVALID_SUPPLIER_ADDRESS("DOMAIN_SUPPLIER_005", "%s khong duoc de trong"),
    INVALID_SUPPLIER_NOTE("DOMAIN_SUPPLIER_006", "%s khong duoc de trong"),
    INVALID_SUPPLIER_CREATED_AT("DOMAIN_SUPPLIER_007", "%s khong duoc nam trong tuong lai"),
    INVALID_SUPPLIER_UPDATED_AT("DOMAIN_SUPPLIER_008", "%s khong duoc nam trong tuong lai"),
    INVALID_SUPPLIER_DELETED_AT("DOMAIN_SUPPLIER_009", "%s khong duoc nam trong tuong lai"),
    INVALID_SUPPLIER_AUDIT_ORDER("DOMAIN_SUPPLIER_010", "%s khong duoc som hon %s"),
    SUPPLIER_ALREADY_DELETED("DOMAIN_SUPPLIER_011", "supplier da bi xoa"),
    SUPPLIER_DATA_NOT_CHANGED("DOMAIN_SUPPLIER_012", "du lieu supplier phai khac du lieu hien tai"),

    INVALID_NOTIFICATION_ID("DOMAIN_NOTIFICATION_001", "%s khong duoc null"),
    INVALID_NOTIFICATION_USER_ID("DOMAIN_NOTIFICATION_002", "%s khong duoc null"),
    INVALID_NOTIFICATION_TITLE("DOMAIN_NOTIFICATION_003", "%s khong duoc de trong"),
    INVALID_NOTIFICATION_CONTENT("DOMAIN_NOTIFICATION_004", "%s khong duoc de trong"),
    INVALID_NOTIFICATION_CREATED_AT("DOMAIN_NOTIFICATION_005", "%s khong duoc nam trong tuong lai"),
    INVALID_NOTIFICATION_UPDATED_AT("DOMAIN_NOTIFICATION_006", "%s khong duoc nam trong tuong lai"),
    INVALID_NOTIFICATION_READ_AT("DOMAIN_NOTIFICATION_007", "%s khong hop le"),
    INVALID_NOTIFICATION_DELETED_AT("DOMAIN_NOTIFICATION_008", "%s khong duoc nam trong tuong lai"),
    INVALID_NOTIFICATION_AUDIT_ORDER("DOMAIN_NOTIFICATION_009", "%s khong duoc som hon %s"),
    NOTIFICATION_ALREADY_DELETED("DOMAIN_NOTIFICATION_010", "thong bao da bi xoa"),
    DELETED_NOTIFICATION_CANNOT_MARK_READ("DOMAIN_NOTIFICATION_011", "thong bao da xoa khong the danh dau da doc"),
    NOTIFICATION_ALREADY_READ("DOMAIN_NOTIFICATION_012", "thong bao da duoc danh dau da doc"),

    INVALID_COUPON_ID("DOMAIN_COUPON_001", "%s khong duoc null"),
    INVALID_COUPON_CODE("DOMAIN_COUPON_002", "%s khong duoc de trong"),
    INVALID_COUPON_DESCRIPTION("DOMAIN_COUPON_003", "%s khong duoc de trong"),
    INVALID_COUPON_DISCOUNT_TYPE("DOMAIN_COUPON_004", "%s khong duoc null"),
    INVALID_COUPON_DISCOUNT_VALUE("DOMAIN_COUPON_005", "%s khong hop le"),
    INVALID_COUPON_MIN_ORDER_AMOUNT("DOMAIN_COUPON_006", "%s khong duoc am"),
    INVALID_COUPON_MAX_DISCOUNT_AMOUNT("DOMAIN_COUPON_007", "%s khong duoc am"),
    INVALID_COUPON_MAX_USAGE_COUNT("DOMAIN_COUPON_008", "%s phai lon hon 0"),
    INVALID_COUPON_USED_COUNT("DOMAIN_COUPON_009", "%s khong duoc am"),
    INVALID_COUPON_STARTS_AT("DOMAIN_COUPON_010", "%s khong duoc null"),
    INVALID_COUPON_EXPIRES_AT("DOMAIN_COUPON_011", "%s khong duoc null"),
    INVALID_COUPON_SCHEDULE("DOMAIN_COUPON_012", "thoi gian bat dau phai som hon thoi gian ket thuc"),
    INVALID_COUPON_CREATED_AT("DOMAIN_COUPON_013", "%s khong duoc nam trong tuong lai"),
    INVALID_COUPON_UPDATED_AT("DOMAIN_COUPON_014", "%s khong duoc nam trong tuong lai"),
    INVALID_COUPON_DELETED_AT("DOMAIN_COUPON_015", "%s khong duoc nam trong tuong lai"),
    INVALID_COUPON_AUDIT_ORDER("DOMAIN_COUPON_016", "%s khong duoc som hon %s"),
    COUPON_ALREADY_DELETED("DOMAIN_COUPON_017", "coupon da bi xoa"),
    COUPON_DATA_NOT_CHANGED("DOMAIN_COUPON_018", "du lieu coupon phai khac du lieu hien tai"),
    COUPON_INACTIVE("DOMAIN_COUPON_019", "coupon khong hoat dong"),
    COUPON_NOT_STARTED("DOMAIN_COUPON_020", "coupon chua den thoi gian ap dung"),
    COUPON_EXPIRED("DOMAIN_COUPON_021", "coupon da het han"),
    COUPON_USAGE_LIMIT_REACHED("DOMAIN_COUPON_022", "coupon da het luot su dung"),
    COUPON_MIN_ORDER_AMOUNT_NOT_REACHED("DOMAIN_COUPON_023", "don hang chua dat gia tri toi thieu de ap dung coupon"),
    INVALID_COUPON_USAGE_ID("DOMAIN_COUPON_USAGE_001", "%s khong duoc null"),
    INVALID_COUPON_USAGE_COUPON_ID("DOMAIN_COUPON_USAGE_002", "%s khong duoc null"),
    INVALID_COUPON_USAGE_USER_ID("DOMAIN_COUPON_USAGE_003", "%s khong duoc null"),
    INVALID_COUPON_USAGE_ORDER_ID("DOMAIN_COUPON_USAGE_004", "%s khong duoc null"),
    INVALID_COUPON_USAGE_USED_AT("DOMAIN_COUPON_USAGE_005", "%s khong duoc nam trong tuong lai"),

    INVALID_BOOK_ID("DOMAIN_BOOK_001", "%s khong duoc null"),
    INVALID_BOOK_TITLE("DOMAIN_BOOK_002", "%s khong duoc de trong"),
    INVALID_BOOK_PRICE("DOMAIN_BOOK_003", "%s khong duoc am"),
    INVALID_BOOK_STOCK_QUANTITY("DOMAIN_BOOK_004", "%s khong duoc am"),
    INVALID_BOOK_CATEGORY_ID("DOMAIN_BOOK_005", "%s khong duoc null"),
    INVALID_BOOK_AUTHOR_ID("DOMAIN_BOOK_006", "%s khong duoc null"),
    INVALID_BOOK_PUBLISHER_ID("DOMAIN_BOOK_007", "%s khong duoc null"),
    INVALID_BOOK_CREATED_AT("DOMAIN_BOOK_008", "%s khong duoc nam trong tuong lai"),
    INVALID_BOOK_UPDATED_AT("DOMAIN_BOOK_009", "%s khong duoc nam trong tuong lai"),
    INVALID_BOOK_DELETED_AT("DOMAIN_BOOK_010", "%s khong duoc nam trong tuong lai"),
    INVALID_BOOK_AUDIT_ORDER("DOMAIN_BOOK_011", "%s khong duoc som hon %s"),
    BOOK_ALREADY_DELETED("DOMAIN_BOOK_012", "book da bi xoa"),
    BOOK_DATA_NOT_CHANGED("DOMAIN_BOOK_013", "du lieu book phai khac du lieu hien tai"),
    INVALID_BOOK_STOCK_DECREASE_QUANTITY("DOMAIN_BOOK_014", "%s phai lon hon 0"),
    BOOK_STOCK_NOT_ENOUGH("DOMAIN_BOOK_015", "ton kho khong du"),
    INVALID_BOOK_STOCK_INCREASE_QUANTITY("DOMAIN_BOOK_016", "%s phai lon hon 0"),

    INVALID_IMPORT_RECEIPT_ID("DOMAIN_IMPORT_RECEIPT_001", "%s khong duoc null"),
    INVALID_IMPORT_RECEIPT_SUPPLIER_ID("DOMAIN_IMPORT_RECEIPT_002", "%s khong duoc null"),
    INVALID_IMPORT_RECEIPT_ITEMS("DOMAIN_IMPORT_RECEIPT_003", "%s khong duoc chua phan tu null"),
    INVALID_IMPORT_RECEIPT_TOTAL_AMOUNT("DOMAIN_IMPORT_RECEIPT_004", "%s khong duoc am"),
    INVALID_IMPORT_RECEIPT_NOTE("DOMAIN_IMPORT_RECEIPT_005", "%s khong duoc de trong"),
    INVALID_IMPORT_RECEIPT_CREATED_AT("DOMAIN_IMPORT_RECEIPT_006", "%s khong duoc nam trong tuong lai"),
    INVALID_IMPORT_RECEIPT_UPDATED_AT("DOMAIN_IMPORT_RECEIPT_007", "%s khong duoc nam trong tuong lai"),
    INVALID_IMPORT_RECEIPT_CREATED_BY("DOMAIN_IMPORT_RECEIPT_008", "%s khong duoc null"),
    INVALID_IMPORT_RECEIPT_AUDIT_ORDER("DOMAIN_IMPORT_RECEIPT_009", "%s khong duoc som hon %s"),
    IMPORT_RECEIPT_MUST_HAVE_AT_LEAST_ONE_ITEM("DOMAIN_IMPORT_RECEIPT_010", "phieu nhap phai co it nhat 1 item"),
    IMPORT_RECEIPT_TOTAL_AMOUNT_MISMATCH("DOMAIN_IMPORT_RECEIPT_011", "tong tien phieu nhap khong khop voi danh sach item"),
    INVALID_IMPORT_RECEIPT_ITEM_ID("DOMAIN_IMPORT_RECEIPT_012", "%s khong duoc null"),
    INVALID_IMPORT_RECEIPT_ITEM_BOOK_ID("DOMAIN_IMPORT_RECEIPT_013", "%s khong duoc null"),
    INVALID_IMPORT_RECEIPT_ITEM_BOOK_TITLE("DOMAIN_IMPORT_RECEIPT_014", "%s khong duoc de trong"),
    INVALID_IMPORT_RECEIPT_ITEM_UNIT_COST("DOMAIN_IMPORT_RECEIPT_015", "%s khong duoc am"),
    INVALID_IMPORT_RECEIPT_ITEM_QUANTITY("DOMAIN_IMPORT_RECEIPT_016", "%s phai lon hon 0"),
    INVALID_IMPORT_RECEIPT_ITEM_LINE_TOTAL("DOMAIN_IMPORT_RECEIPT_017", "%s khong duoc am"),
    IMPORT_RECEIPT_ITEM_LINE_TOTAL_MISMATCH("DOMAIN_IMPORT_RECEIPT_018", "tong tien item phieu nhap khong khop don gia va so luong"),

    INVALID_CART_ID("DOMAIN_CART_001", "%s khong duoc null"),
    INVALID_CART_USER_ID("DOMAIN_CART_002", "%s khong duoc null"),
    INVALID_CART_ITEMS("DOMAIN_CART_003", "%s khong duoc chua phan tu null"),
    INVALID_CART_CREATED_AT("DOMAIN_CART_004", "%s khong duoc nam trong tuong lai"),
    INVALID_CART_UPDATED_AT("DOMAIN_CART_005", "%s khong duoc nam trong tuong lai"),
    INVALID_CART_AUDIT_ORDER("DOMAIN_CART_006", "%s khong duoc som hon %s"),
    INVALID_CART_ITEM_ID("DOMAIN_CART_007", "%s khong duoc null"),
    INVALID_CART_ITEM_BOOK_ID("DOMAIN_CART_008", "%s khong duoc null"),
    INVALID_CART_ITEM_QUANTITY("DOMAIN_CART_009", "%s phai lon hon 0"),
    INVALID_CART_ITEM_CREATED_AT("DOMAIN_CART_010", "%s khong duoc nam trong tuong lai"),
    INVALID_CART_ITEM_UPDATED_AT("DOMAIN_CART_011", "%s khong duoc nam trong tuong lai"),
    INVALID_CART_ITEM_AUDIT_ORDER("DOMAIN_CART_012", "%s khong duoc som hon %s"),
    CART_ITEM_NOT_FOUND("DOMAIN_CART_013", "khong tim thay sach trong gio hang"),
    CART_ITEM_QUANTITY_EXCEEDS_STOCK("DOMAIN_CART_014", "so luong vuot qua ton kho"),

    INVALID_ORDER_ID("DOMAIN_ORDER_001", "%s khong duoc null"),
    INVALID_ORDER_USER_ID("DOMAIN_ORDER_002", "%s khong duoc null"),
    INVALID_ORDER_ITEMS("DOMAIN_ORDER_003", "%s khong duoc chua phan tu null"),
    INVALID_ORDER_TOTAL_AMOUNT("DOMAIN_ORDER_004", "%s khong duoc am"),
    INVALID_ORDER_DISCOUNT_AMOUNT("DOMAIN_ORDER_005", "%s khong duoc am"),
    INVALID_ORDER_SHIPPING_FEE("DOMAIN_ORDER_006", "%s khong duoc am"),
    INVALID_ORDER_FINAL_AMOUNT("DOMAIN_ORDER_007", "%s khong duoc am"),
    INVALID_ORDER_COUPON_CODE("DOMAIN_ORDER_008", "%s khong duoc de trong"),
    INVALID_ORDER_PAYMENT_METHOD("DOMAIN_ORDER_009", "%s khong duoc null"),
    INVALID_ORDER_PAYMENT_STATUS("DOMAIN_ORDER_010", "%s khong duoc null"),
    INVALID_ORDER_STATUS("DOMAIN_ORDER_011", "%s khong duoc null"),
    INVALID_ORDER_RECEIVER_NAME("DOMAIN_ORDER_012", "%s khong duoc de trong"),
    INVALID_ORDER_RECEIVER_PHONE("DOMAIN_ORDER_013", "%s phai co dung 10 chu so va bat dau bang 0"),
    INVALID_ORDER_RECEIVER_ADDRESS("DOMAIN_ORDER_014", "%s khong duoc de trong"),
    INVALID_ORDER_CREATED_AT("DOMAIN_ORDER_015", "%s khong duoc nam trong tuong lai"),
    INVALID_ORDER_UPDATED_AT("DOMAIN_ORDER_016", "%s khong duoc nam trong tuong lai"),
    INVALID_ORDER_CANCELLED_AT("DOMAIN_ORDER_017", "%s khong duoc nam trong tuong lai"),
    INVALID_ORDER_AUDIT_ORDER("DOMAIN_ORDER_018", "%s khong duoc som hon %s"),
    ORDER_MUST_HAVE_AT_LEAST_ONE_ITEM("DOMAIN_ORDER_019", "order phai co it nhat 1 item"),
    ORDER_TOTAL_AMOUNT_MISMATCH("DOMAIN_ORDER_020", "tong tien order khong khop voi danh sach item"),
    ORDER_FINAL_AMOUNT_MISMATCH("DOMAIN_ORDER_021", "so tien cuoi cung khong khop tong tien, giam gia va phi ship"),
    DELIVERED_ORDER_CANNOT_BE_CANCELLED("DOMAIN_ORDER_022", "don hang da giao khong the huy"),
    CANCELLED_ORDER_CANNOT_BE_UPDATED("DOMAIN_ORDER_023", "don hang da huy khong the cap nhat"),
    INVALID_ORDER_STATUS_TRANSITION("DOMAIN_ORDER_024", "khong the chuyen trang thai tu %s sang %s"),
    ORDER_STATUS_NOT_CHANGED("DOMAIN_ORDER_025", "trang thai order phai khac trang thai hien tai"),
    INVALID_ORDER_ITEM_ID("DOMAIN_ORDER_026", "%s khong duoc null"),
    INVALID_ORDER_ITEM_BOOK_ID("DOMAIN_ORDER_027", "%s khong duoc null"),
    INVALID_ORDER_ITEM_BOOK_TITLE("DOMAIN_ORDER_028", "%s khong duoc de trong"),
    INVALID_ORDER_ITEM_UNIT_PRICE("DOMAIN_ORDER_029", "%s khong duoc am"),
    INVALID_ORDER_ITEM_QUANTITY("DOMAIN_ORDER_030", "%s phai lon hon 0"),
    INVALID_ORDER_ITEM_LINE_TOTAL("DOMAIN_ORDER_031", "%s khong duoc am"),
    ORDER_ITEM_LINE_TOTAL_MISMATCH("DOMAIN_ORDER_032", "tong tien item khong khop don gia va so luong"),

    INVALID_ROLE_ID("DOMAIN_ROLE_001", "%s khong duoc null"),
    INVALID_ROLE_NAME("DOMAIN_ROLE_002", "%s khong duoc null"),
    INVALID_ROLE_DESCRIPTION("DOMAIN_ROLE_003", "%s khong duoc de trong"),
    INVALID_ROLE_PERMISSIONS("DOMAIN_ROLE_004", "%s khong duoc chua phan tu null"),
    INVALID_ROLE_CREATED_AT("DOMAIN_ROLE_005", "%s khong duoc nam trong tuong lai"),
    INVALID_ROLE_UPDATED_AT("DOMAIN_ROLE_006", "%s khong duoc nam trong tuong lai"),
    INVALID_ROLE_DELETED_AT("DOMAIN_ROLE_007", "%s khong duoc nam trong tuong lai"),
    INVALID_ROLE_AUDIT_ORDER("DOMAIN_ROLE_008", "%s khong duoc som hon %s"),
    ROLE_ALREADY_DELETED("DOMAIN_ROLE_009", "role da bi xoa"),
    ROLE_DATA_NOT_CHANGED("DOMAIN_ROLE_010", "du lieu role phai khac du lieu hien tai"),

    INVALID_PERMISSION_ID("DOMAIN_PERMISSION_001", "%s khong duoc null"),
    INVALID_PERMISSION_CODE("DOMAIN_PERMISSION_002", "%s khong duoc null"),
    INVALID_PERMISSION_DESCRIPTION("DOMAIN_PERMISSION_003", "%s khong duoc de trong"),
    INVALID_PERMISSION_CREATED_AT("DOMAIN_PERMISSION_004", "%s khong duoc nam trong tuong lai"),
    INVALID_PERMISSION_UPDATED_AT("DOMAIN_PERMISSION_005", "%s khong duoc nam trong tuong lai"),
    INVALID_PERMISSION_DELETED_AT("DOMAIN_PERMISSION_006", "%s khong duoc nam trong tuong lai"),
    INVALID_PERMISSION_AUDIT_ORDER("DOMAIN_PERMISSION_007", "%s khong duoc som hon %s"),
    PERMISSION_ALREADY_DELETED("DOMAIN_PERMISSION_008", "permission da bi xoa"),
    PERMISSION_CODE_NOT_CHANGED("DOMAIN_PERMISSION_009", "code permission phai khac code hien tai"),
    PERMISSION_DATA_NOT_CHANGED("DOMAIN_PERMISSION_010", "du lieu permission phai khac du lieu hien tai"),

    INVALID_REFRESH_TOKEN_ID("DOMAIN_REFRESH_TOKEN_001", "%s khong duoc null"),
    INVALID_REFRESH_TOKEN_USER_ID("DOMAIN_REFRESH_TOKEN_002", "%s khong duoc null"),
    INVALID_REFRESH_TOKEN_TOKEN("DOMAIN_REFRESH_TOKEN_003", "%s khong duoc de trong"),
    INVALID_REFRESH_TOKEN_EXPIRES_AT("DOMAIN_REFRESH_TOKEN_004", "%s phai nam trong tuong lai"),
    INVALID_REFRESH_TOKEN_CREATED_AT("DOMAIN_REFRESH_TOKEN_005", "%s khong duoc nam trong tuong lai"),
    INVALID_REFRESH_TOKEN_AUDIT_ORDER("DOMAIN_REFRESH_TOKEN_006", "%s phai sau %s"),

    INVALID_REVIEW_ID("DOMAIN_REVIEW_001", "%s khong duoc null"),
    INVALID_REVIEW_USER_ID("DOMAIN_REVIEW_002", "%s khong duoc null"),
    INVALID_REVIEW_BOOK_ID("DOMAIN_REVIEW_003", "%s khong duoc null"),
    INVALID_REVIEW_ORDER_ITEM_ID("DOMAIN_REVIEW_004", "%s khong duoc null"),
    INVALID_REVIEW_RATING("DOMAIN_REVIEW_005", "%s phai tu 1 den 5"),
    INVALID_REVIEW_COMMENT("DOMAIN_REVIEW_006", "%s khong duoc vuot qua 1000 ky tu"),
    INVALID_REVIEW_CREATED_AT("DOMAIN_REVIEW_007", "%s khong duoc nam trong tuong lai"),
    INVALID_REVIEW_UPDATED_AT("DOMAIN_REVIEW_008", "%s khong duoc nam trong tuong lai"),
    INVALID_REVIEW_DELETED_AT("DOMAIN_REVIEW_009", "%s khong duoc nam trong tuong lai"),
    INVALID_REVIEW_AUDIT_ORDER("DOMAIN_REVIEW_010", "%s khong duoc som hon %s"),
    REVIEW_ALREADY_DELETED("DOMAIN_REVIEW_011", "review da bi xoa"),
    DELETED_REVIEW_CANNOT_UPDATE("DOMAIN_REVIEW_012", "review da xoa khong the cap nhat"),

    INVALID_STOCK_MOVEMENT_ID("DOMAIN_STOCK_MOVEMENT_001", "%s khong duoc null"),
    INVALID_STOCK_MOVEMENT_BOOK_ID("DOMAIN_STOCK_MOVEMENT_002", "%s khong duoc null"),
    INVALID_STOCK_MOVEMENT_TYPE("DOMAIN_STOCK_MOVEMENT_003", "%s khong duoc null"),
    INVALID_STOCK_MOVEMENT_QUANTITY("DOMAIN_STOCK_MOVEMENT_004", "%s phai lon hon 0"),
    INVALID_STOCK_MOVEMENT_BEFORE_QUANTITY("DOMAIN_STOCK_MOVEMENT_005", "%s khong duoc am"),
    INVALID_STOCK_MOVEMENT_AFTER_QUANTITY("DOMAIN_STOCK_MOVEMENT_006", "%s khong duoc am"),
    INVALID_STOCK_MOVEMENT_REFERENCE_TYPE("DOMAIN_STOCK_MOVEMENT_007", "%s khong duoc de trong"),
    INVALID_STOCK_MOVEMENT_NOTE("DOMAIN_STOCK_MOVEMENT_008", "%s khong duoc de trong"),
    INVALID_STOCK_MOVEMENT_CREATED_AT("DOMAIN_STOCK_MOVEMENT_009", "%s khong duoc nam trong tuong lai"),
    INVALID_STOCK_MOVEMENT_CREATED_BY("DOMAIN_STOCK_MOVEMENT_010", "%s khong duoc null"),
    STOCK_MOVEMENT_QUANTITY_MISMATCH("DOMAIN_STOCK_MOVEMENT_011", "so luong bien dong khong khop ton truoc va sau");

    private final String code;
    private final String messageTemplate;

    DomainErrorCode(String code, String messageTemplate) {
        this.code = code;
        this.messageTemplate = messageTemplate;
    }

    public String getCode() {
        return code;
    }

    public String message(Object... args) {
        return String.format(messageTemplate, args);
    }
}
