package com.bookstore.bookstore.domain.exception;

public enum DomainErrorCode {

    INVALID_USER_ID("DOMAIN_USER_001", "%s không được null"),
    INVALID_USER_USERNAME("DOMAIN_USER_002", "%s không được để trống"),
    INVALID_USER_PASSWORD_HASH("DOMAIN_USER_003", "%s không được để trống"),
    INVALID_USER_PHONE_NUMBER("DOMAIN_USER_004", "%s phải có đúng 10 chữ số và bắt đầu bằng 0"),
    INVALID_USER_EMAIL("DOMAIN_USER_005", "%s không đúng định dạng email"),
    INVALID_USER_STATUS("DOMAIN_USER_006", "%s không được null"),
    INVALID_USER_ROLES("DOMAIN_USER_007", "%s không được chứa phần tử null"),
    INVALID_USER_CREATED_AT("DOMAIN_USER_008", "%s không được nằm trong tương lai"),
    INVALID_USER_UPDATED_AT("DOMAIN_USER_009", "%s không được nằm trong tương lai"),
    INVALID_USER_DELETED_AT("DOMAIN_USER_010", "%s không được nằm trong tương lai"),
    INVALID_USER_AUDIT_ORDER("DOMAIN_USER_011", "%s không được sớm hơn %s"),
    USER_ALREADY_EXISTS("DOMAIN_USER_012", "user đã tồn tại"),
    USER_NOT_FOUND("DOMAIN_USER_013", "không tìm thấy user"),
    USER_USERNAME_ALREADY_EXISTS("DOMAIN_USER_014", "username đã tồn tại"),
    USER_ALREADY_ACTIVE("DOMAIN_USER_015", "user đã được kích hoạt"),
    BLOCKED_USER_CANNOT_BE_ACTIVATED("DOMAIN_USER_016", "tài khoản bi khoa không thể kích hoạt"),
    DELETED_USER_CANNOT_BE_ACTIVATED("DOMAIN_USER_017", "tài khoản đã xóa không thể kích hoạt"),
    USER_ALREADY_DELETED("DOMAIN_USER_018", "user đã bi xóa"),
    USER_NOT_ACTIVE_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_019", "tài khoản không hoat đóng không thể cập nhật thong tin"),
    BLOCKED_USER_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_020", "tài khoản bi khoa không thể cập nhật thong tin"),
    DELETED_USER_CANNOT_UPDATE_ACCOUNT_INFO("DOMAIN_USER_021", "tài khoản đã xóa không thể cập nhật thong tin"),
    USER_PHONE_ALREADY_EXISTS("DOMAIN_USER_022", "phoneNumber đã tồn tại"),
    USER_EMAIL_ALREADY_EXISTS("DOMAIN_USER_023", "email đã tồn tại"),
    USER_NOT_ACTIVE_CANNOT_LOGIN("DOMAIN_USER_024", "tài khoản không hoat đóng không thể đăng nhập"),
    BLOCKED_USER_CANNOT_LOGIN("DOMAIN_USER_025", "tài khoản bi khoa không thể đăng nhập"),
    DELETED_USER_CANNOT_LOGIN("DOMAIN_USER_026", "tài khoản đã xóa không thể đăng nhập"),
    DELETED_USER_CANNOT_UPDATE_LOCK_STATUS("DOMAIN_USER_027", "tài khoản đã xóa không thể khoa hoặc mo khoa"),
    USER_LOCK_STATUS_NOT_CHANGED("DOMAIN_USER_028", "trang thai khoa tài khoản phải khác hiện tại"),
    USER_MANAGED_INFO_NOT_CHANGED("DOMAIN_USER_029", "thong tin user phải khác dữ liệu hiện tại"),

    INVALID_USER_AUTH_IDENTITY_ID("DOMAIN_USER_AUTH_IDENTITY_001", "%s không được null"),
    INVALID_USER_AUTH_IDENTITY_USER_ID("DOMAIN_USER_AUTH_IDENTITY_002", "%s không được null"),
    INVALID_USER_AUTH_IDENTITY_PROVIDER("DOMAIN_USER_AUTH_IDENTITY_003", "%s không được null"),
    INVALID_USER_AUTH_IDENTITY_PROVIDER_SUBJECT("DOMAIN_USER_AUTH_IDENTITY_004", "%s không được để trống"),
    INVALID_USER_AUTH_IDENTITY_PROVIDER_EMAIL("DOMAIN_USER_AUTH_IDENTITY_005", "%s không đúng định dạng email"),
    INVALID_USER_AUTH_IDENTITY_CREATED_AT("DOMAIN_USER_AUTH_IDENTITY_006", "%s không được nằm trong tương lai"),
    INVALID_USER_AUTH_IDENTITY_UPDATED_AT("DOMAIN_USER_AUTH_IDENTITY_007", "%s không được nằm trong tương lai"),
    INVALID_USER_AUTH_IDENTITY_AUDIT_ORDER("DOMAIN_USER_AUTH_IDENTITY_008", "%s không được sớm hơn %s"),

    INVALID_USER_OTP_ID("DOMAIN_USER_OTP_001", "%s không được null"),
    INVALID_USER_OTP_USER_ID("DOMAIN_USER_OTP_002", "%s không được null"),
    INVALID_USER_OTP_HASH("DOMAIN_USER_OTP_003", "%s không được để trống"),
    INVALID_USER_OTP_EXPIRES_AT("DOMAIN_USER_OTP_004", "%s không được null"),
    INVALID_USER_OTP_CREATED_AT("DOMAIN_USER_OTP_005", "%s không được nằm trong tương lai"),
    INVALID_USER_OTP_UPDATED_AT("DOMAIN_USER_OTP_006", "%s không được nằm trong tương lai"),
    INVALID_USER_OTP_VERIFIED_AT("DOMAIN_USER_OTP_007", "%s không được nằm trong tương lai"),
    INVALID_USER_OTP_INVALIDATED_AT("DOMAIN_USER_OTP_008", "%s không được nằm trong tương lai"),
    INVALID_USER_OTP_AUDIT_ORDER("DOMAIN_USER_OTP_009", "%s không được sớm hơn %s"),
    INVALID_USER_OTP_PURPOSE("DOMAIN_USER_OTP_010", "%s không được null"),

    INVALID_PROFILE_ID("DOMAIN_PROFILE_001", "%s không được null"),
    INVALID_PROFILE_USER_ID("DOMAIN_PROFILE_002", "%s không được null"),
    INVALID_PROFILE_LAST_NAME("DOMAIN_PROFILE_003", "%s không được để trống"),
    INVALID_PROFILE_FIRST_NAME("DOMAIN_PROFILE_004", "%s không được để trống"),
    INVALID_PROFILE_AVATAR_URL("DOMAIN_PROFILE_005", "%s không được để trống"),
    INVALID_PROFILE_AVATAR_FILE_ASSET_ID("DOMAIN_PROFILE_018", "%s không được hop le"),
    INVALID_PROFILE_GENDER("DOMAIN_PROFILE_006", "%s không được null"),
    INVALID_PROFILE_DATE_OF_BIRTH("DOMAIN_PROFILE_007", "%s không được nằm trong tương lai"),
    INVALID_PROFILE_CREATED_AT("DOMAIN_PROFILE_008", "%s không được nằm trong tương lai"),
    INVALID_PROFILE_UPDATED_AT("DOMAIN_PROFILE_009", "%s không được nằm trong tương lai"),
    INVALID_PROFILE_DELETED_AT("DOMAIN_PROFILE_010", "%s không được nằm trong tương lai"),
    INVALID_PROFILE_AUDIT_ORDER("DOMAIN_PROFILE_011", "%s không được sớm hơn %s"),
    PROFILE_ALREADY_EXISTS("DOMAIN_PROFILE_012", "profile đã tồn tại"),
    PROFILE_NOT_FOUND("DOMAIN_PROFILE_013", "không tìm thấy profile"),
    PROFILE_USER_NOT_FOUND("DOMAIN_PROFILE_014", "không tìm thấy user"),
    PROFILE_USER_ALREADY_HAS_PROFILE("DOMAIN_PROFILE_015", "user đã có profile"),
    PROFILE_ALREADY_DELETED("DOMAIN_PROFILE_016", "profile đã bi xóa"),
    DELETED_PROFILE_CANNOT_UPDATE_PROFILE_INFO("DOMAIN_PROFILE_017", "profile đã xóa không thể cập nhật thong tin"),

    INVALID_USER_ADDRESS_ID("DOMAIN_USER_ADDRESS_001", "%s không được null"),
    INVALID_USER_ADDRESS_USER_ID("DOMAIN_USER_ADDRESS_002", "%s không được null"),
    INVALID_USER_ADDRESS_RECEIVER_NAME("DOMAIN_USER_ADDRESS_003", "%s không được để trống"),
    INVALID_USER_ADDRESS_RECEIVER_PHONE("DOMAIN_USER_ADDRESS_004", "%s phải có đúng 10 chữ số và bắt đầu bằng 0"),
    INVALID_USER_ADDRESS_RECEIVER_ADDRESS("DOMAIN_USER_ADDRESS_005", "%s không được để trống"),
    INVALID_USER_ADDRESS_CREATED_AT("DOMAIN_USER_ADDRESS_006", "%s không được nằm trong tương lai"),
    INVALID_USER_ADDRESS_UPDATED_AT("DOMAIN_USER_ADDRESS_007", "%s không được nằm trong tương lai"),
    INVALID_USER_ADDRESS_DELETED_AT("DOMAIN_USER_ADDRESS_008", "%s không được nằm trong tương lai"),
    INVALID_USER_ADDRESS_AUDIT_ORDER("DOMAIN_USER_ADDRESS_009", "%s không được sớm hơn %s"),
    USER_ADDRESS_ALREADY_DELETED("DOMAIN_USER_ADDRESS_010", "địa chỉ nhận hàng đã bi xóa"),
    DELETED_USER_ADDRESS_CANNOT_UPDATE("DOMAIN_USER_ADDRESS_011", "địa chỉ nhận hàng đã xóa không thể cập nhật"),
    DELETED_USER_ADDRESS_CANNOT_SET_DEFAULT("DOMAIN_USER_ADDRESS_012", "địa chỉ nhận hàng đã xóa không thể dat mac dinh"),

    INVALID_CATEGORY_ID("DOMAIN_CATEGORY_001", "%s không được null"),
    INVALID_CATEGORY_NAME("DOMAIN_CATEGORY_002", "%s không được để trống"),
    INVALID_CATEGORY_CREATED_AT("DOMAIN_CATEGORY_003", "%s không được nằm trong tương lai"),
    INVALID_CATEGORY_UPDATED_AT("DOMAIN_CATEGORY_004", "%s không được nằm trong tương lai"),
    INVALID_CATEGORY_DELETED_AT("DOMAIN_CATEGORY_005", "%s không được nằm trong tương lai"),
    INVALID_CATEGORY_AUDIT_ORDER("DOMAIN_CATEGORY_006", "%s không được sớm hơn %s"),
    CATEGORY_ALREADY_DELETED("DOMAIN_CATEGORY_007", "category đã bi xóa"),
    CATEGORY_DATA_NOT_CHANGED("DOMAIN_CATEGORY_008", "dữ liệu category phải khác dữ liệu hiện tại"),
    INVALID_CATEGORY_PARENT_ID("DOMAIN_CATEGORY_009", "%s không hợp lệ"),

    INVALID_AUTHOR_ID("DOMAIN_AUTHOR_001", "%s không được null"),
    INVALID_AUTHOR_NAME("DOMAIN_AUTHOR_002", "%s không được để trống"),
    INVALID_AUTHOR_CREATED_AT("DOMAIN_AUTHOR_003", "%s không được nằm trong tương lai"),
    INVALID_AUTHOR_UPDATED_AT("DOMAIN_AUTHOR_004", "%s không được nằm trong tương lai"),
    INVALID_AUTHOR_DELETED_AT("DOMAIN_AUTHOR_005", "%s không được nằm trong tương lai"),
    INVALID_AUTHOR_AUDIT_ORDER("DOMAIN_AUTHOR_006", "%s không được sớm hơn %s"),
    AUTHOR_ALREADY_DELETED("DOMAIN_AUTHOR_007", "author đã bi xóa"),
    AUTHOR_DATA_NOT_CHANGED("DOMAIN_AUTHOR_008", "dữ liệu author phải khác dữ liệu hiện tại"),
    INVALID_AUTHOR_AVATAR_URL("DOMAIN_AUTHOR_009", "%s không được để trống"),
    INVALID_AUTHOR_AVATAR_FILE_ASSET_ID("DOMAIN_AUTHOR_013", "%s không được hop le"),
    INVALID_AUTHOR_BIRTH_YEAR("DOMAIN_AUTHOR_010", "%s phải lớn hơn 0"),
    INVALID_AUTHOR_DEATH_YEAR("DOMAIN_AUTHOR_011", "%s phải lớn hơn 0"),
    INVALID_AUTHOR_LIFESPAN("DOMAIN_AUTHOR_012", "deathYear không được nho hon birthYear"),

    INVALID_PUBLISHER_ID("DOMAIN_PUBLISHER_001", "%s không được null"),
    INVALID_PUBLISHER_NAME("DOMAIN_PUBLISHER_002", "%s không được để trống"),
    INVALID_PUBLISHER_CREATED_AT("DOMAIN_PUBLISHER_003", "%s không được nằm trong tương lai"),
    INVALID_PUBLISHER_UPDATED_AT("DOMAIN_PUBLISHER_004", "%s không được nằm trong tương lai"),
    INVALID_PUBLISHER_DELETED_AT("DOMAIN_PUBLISHER_005", "%s không được nằm trong tương lai"),
    INVALID_PUBLISHER_AUDIT_ORDER("DOMAIN_PUBLISHER_006", "%s không được sớm hơn %s"),
    PUBLISHER_ALREADY_DELETED("DOMAIN_PUBLISHER_007", "publisher đã bi xóa"),
    PUBLISHER_DATA_NOT_CHANGED("DOMAIN_PUBLISHER_008", "dữ liệu publisher phải khác dữ liệu hiện tại"),

    INVALID_SUPPLIER_ID("DOMAIN_SUPPLIER_001", "%s không được null"),
    INVALID_SUPPLIER_NAME("DOMAIN_SUPPLIER_002", "%s không được để trống"),
    INVALID_SUPPLIER_PHONE("DOMAIN_SUPPLIER_003", "%s phải có đúng 10 chữ số và bắt đầu bằng 0"),
    INVALID_SUPPLIER_EMAIL("DOMAIN_SUPPLIER_004", "%s không đúng định dạng email"),
    INVALID_SUPPLIER_ADDRESS("DOMAIN_SUPPLIER_005", "%s không được để trống"),
    INVALID_SUPPLIER_NOTE("DOMAIN_SUPPLIER_006", "%s không được để trống"),
    INVALID_SUPPLIER_CREATED_AT("DOMAIN_SUPPLIER_007", "%s không được nằm trong tương lai"),
    INVALID_SUPPLIER_UPDATED_AT("DOMAIN_SUPPLIER_008", "%s không được nằm trong tương lai"),
    INVALID_SUPPLIER_DELETED_AT("DOMAIN_SUPPLIER_009", "%s không được nằm trong tương lai"),
    INVALID_SUPPLIER_AUDIT_ORDER("DOMAIN_SUPPLIER_010", "%s không được sớm hơn %s"),
    SUPPLIER_ALREADY_DELETED("DOMAIN_SUPPLIER_011", "supplier đã bi xóa"),
    SUPPLIER_DATA_NOT_CHANGED("DOMAIN_SUPPLIER_012", "dữ liệu supplier phải khác dữ liệu hiện tại"),

    INVALID_NOTIFICATION_ID("DOMAIN_NOTIFICATION_001", "%s không được null"),
    INVALID_NOTIFICATION_USER_ID("DOMAIN_NOTIFICATION_002", "%s không được null"),
    INVALID_NOTIFICATION_TITLE("DOMAIN_NOTIFICATION_003", "%s không được để trống"),
    INVALID_NOTIFICATION_CONTENT("DOMAIN_NOTIFICATION_004", "%s không được để trống"),
    INVALID_NOTIFICATION_CREATED_AT("DOMAIN_NOTIFICATION_005", "%s không được nằm trong tương lai"),
    INVALID_NOTIFICATION_UPDATED_AT("DOMAIN_NOTIFICATION_006", "%s không được nằm trong tương lai"),
    INVALID_NOTIFICATION_READ_AT("DOMAIN_NOTIFICATION_007", "%s không hợp lệ"),
    INVALID_NOTIFICATION_DELETED_AT("DOMAIN_NOTIFICATION_008", "%s không được nằm trong tương lai"),
    INVALID_NOTIFICATION_AUDIT_ORDER("DOMAIN_NOTIFICATION_009", "%s không được sớm hơn %s"),
    NOTIFICATION_ALREADY_DELETED("DOMAIN_NOTIFICATION_010", "thông báo đã bi xóa"),
    DELETED_NOTIFICATION_CANNOT_MARK_READ("DOMAIN_NOTIFICATION_011", "thông báo đã xóa không thể danh dau đã doc"),
    NOTIFICATION_ALREADY_READ("DOMAIN_NOTIFICATION_012", "thông báo đã được danh dau đã doc"),

    INVALID_CONVERSATION_ID("DOMAIN_CHAT_CONVERSATION_001", "%s không được null"),
    INVALID_CONVERSATION_CUSTOMER_ID("DOMAIN_CHAT_CONVERSATION_002", "%s không được null"),
    INVALID_CONVERSATION_STATUS("DOMAIN_CHAT_CONVERSATION_003", "%s không được null"),
    INVALID_CONVERSATION_SUBJECT("DOMAIN_CHAT_CONVERSATION_004", "%s không được để trống"),
    INVALID_CONVERSATION_PRIORITY("DOMAIN_CHAT_CONVERSATION_005", "%s không được null"),
    INVALID_CONVERSATION_TARGET_TYPE("DOMAIN_CHAT_CONVERSATION_006", "%s không được null"),
    INVALID_CONVERSATION_CREATED_AT("DOMAIN_CHAT_CONVERSATION_007", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_UPDATED_AT("DOMAIN_CHAT_CONVERSATION_008", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_LAST_MESSAGE_AT("DOMAIN_CHAT_CONVERSATION_009", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_CLOSED_AT("DOMAIN_CHAT_CONVERSATION_010", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_DELETED_AT("DOMAIN_CHAT_CONVERSATION_011", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_AUDIT_ORDER("DOMAIN_CHAT_CONVERSATION_012", "%s không được sớm hơn %s"),
    CONVERSATION_ALREADY_DELETED("DOMAIN_CHAT_CONVERSATION_013", "cuộc trò chuyện đã bi xóa"),
    CONVERSATION_ALREADY_CLOSED("DOMAIN_CHAT_CONVERSATION_014", "cuộc trò chuyện đã đóng"),
    CONVERSATION_NOT_CLOSED("DOMAIN_CHAT_CONVERSATION_015", "cuộc trò chuyện chưa đóng"),
    CONVERSATION_CLOSED_CANNOT_SEND_MESSAGE("DOMAIN_CHAT_CONVERSATION_016", "cuộc trò chuyện đã đóng không thể gửi tin nhắn"),

    INVALID_CHAT_MESSAGE_ID("DOMAIN_CHAT_MESSAGE_001", "%s không được null"),
    INVALID_CHAT_MESSAGE_CONVERSATION_ID("DOMAIN_CHAT_MESSAGE_002", "%s không được null"),
    INVALID_CHAT_MESSAGE_SENDER_ID("DOMAIN_CHAT_MESSAGE_003", "%s không được null"),
    INVALID_CHAT_MESSAGE_SENDER_ROLE("DOMAIN_CHAT_MESSAGE_004", "%s không được null"),
    INVALID_CHAT_MESSAGE_TYPE("DOMAIN_CHAT_MESSAGE_005", "%s không được null"),
    INVALID_CHAT_MESSAGE_CONTENT("DOMAIN_CHAT_MESSAGE_006", "%s không được để trống"),
    INVALID_CHAT_MESSAGE_ATTACHMENT_SIZE("DOMAIN_CHAT_MESSAGE_007", "%s không được âm"),
    INVALID_CHAT_MESSAGE_CREATED_AT("DOMAIN_CHAT_MESSAGE_008", "%s không được nằm trong tương lai"),
    INVALID_CHAT_MESSAGE_UPDATED_AT("DOMAIN_CHAT_MESSAGE_009", "%s không được nằm trong tương lai"),
    INVALID_CHAT_MESSAGE_DELETED_AT("DOMAIN_CHAT_MESSAGE_010", "%s không được nằm trong tương lai"),
    INVALID_CHAT_MESSAGE_AUDIT_ORDER("DOMAIN_CHAT_MESSAGE_011", "%s không được sớm hơn %s"),
    CHAT_MESSAGE_ALREADY_DELETED("DOMAIN_CHAT_MESSAGE_012", "tin nhắn đã bi xóa"),

    INVALID_CONVERSATION_PARTICIPANT_ID("DOMAIN_CHAT_PARTICIPANT_001", "%s không được null"),
    INVALID_CONVERSATION_PARTICIPANT_CONVERSATION_ID("DOMAIN_CHAT_PARTICIPANT_002", "%s không được null"),
    INVALID_CONVERSATION_PARTICIPANT_USER_ID("DOMAIN_CHAT_PARTICIPANT_003", "%s không được null"),
    INVALID_CONVERSATION_PARTICIPANT_ROLE("DOMAIN_CHAT_PARTICIPANT_004", "%s không được null"),
    INVALID_CONVERSATION_PARTICIPANT_UNREAD_COUNT("DOMAIN_CHAT_PARTICIPANT_005", "%s không được âm"),
    INVALID_CONVERSATION_PARTICIPANT_JOINED_AT("DOMAIN_CHAT_PARTICIPANT_006", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_PARTICIPANT_LAST_READ_AT("DOMAIN_CHAT_PARTICIPANT_007", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_PARTICIPANT_LEFT_AT("DOMAIN_CHAT_PARTICIPANT_008", "%s không được nằm trong tương lai"),
    INVALID_CONVERSATION_PARTICIPANT_AUDIT_ORDER("DOMAIN_CHAT_PARTICIPANT_009", "%s không được sớm hơn %s"),
    CONVERSATION_PARTICIPANT_ALREADY_LEFT("DOMAIN_CHAT_PARTICIPANT_010", "nguoi tham gia đã roi cuộc trò chuyện"),

    INVALID_COUPON_ID("DOMAIN_COUPON_001", "%s không được null"),
    INVALID_COUPON_CODE("DOMAIN_COUPON_002", "%s không được để trống"),
    INVALID_COUPON_DESCRIPTION("DOMAIN_COUPON_003", "%s không được để trống"),
    INVALID_COUPON_DISCOUNT_TYPE("DOMAIN_COUPON_004", "%s không được null"),
    INVALID_COUPON_DISCOUNT_VALUE("DOMAIN_COUPON_005", "%s không hợp lệ"),
    INVALID_COUPON_MIN_ORDER_AMOUNT("DOMAIN_COUPON_006", "%s không được âm"),
    INVALID_COUPON_MAX_DISCOUNT_AMOUNT("DOMAIN_COUPON_007", "%s không được âm"),
    INVALID_COUPON_MAX_USAGE_COUNT("DOMAIN_COUPON_008", "%s phải lớn hơn 0"),
    INVALID_COUPON_USED_COUNT("DOMAIN_COUPON_009", "%s không được âm"),
    INVALID_COUPON_STARTS_AT("DOMAIN_COUPON_010", "%s không được null"),
    INVALID_COUPON_EXPIRES_AT("DOMAIN_COUPON_011", "%s không được null"),
    INVALID_COUPON_SCHEDULE("DOMAIN_COUPON_012", "thoi gian bắt đầu phải sớm hơn thoi gian kết thúc"),
    INVALID_COUPON_CREATED_AT("DOMAIN_COUPON_013", "%s không được nằm trong tương lai"),
    INVALID_COUPON_UPDATED_AT("DOMAIN_COUPON_014", "%s không được nằm trong tương lai"),
    INVALID_COUPON_DELETED_AT("DOMAIN_COUPON_015", "%s không được nằm trong tương lai"),
    INVALID_COUPON_AUDIT_ORDER("DOMAIN_COUPON_016", "%s không được sớm hơn %s"),
    COUPON_ALREADY_DELETED("DOMAIN_COUPON_017", "coupon đã bi xóa"),
    COUPON_DATA_NOT_CHANGED("DOMAIN_COUPON_018", "dữ liệu coupon phải khác dữ liệu hiện tại"),
    COUPON_INACTIVE("DOMAIN_COUPON_019", "coupon không hoat đóng"),
    COUPON_NOT_STARTED("DOMAIN_COUPON_020", "coupon chưa den thoi gian áp dụng"),
    COUPON_EXPIRED("DOMAIN_COUPON_021", "coupon đã hết hạn"),
    COUPON_USAGE_LIMIT_REACHED("DOMAIN_COUPON_022", "coupon đã het luot sử dụng"),
    COUPON_MIN_ORDER_AMOUNT_NOT_REACHED("DOMAIN_COUPON_023", "đơn hàng chưa dat gia tri toi thieu de áp dụng coupon"),
    INVALID_COUPON_TYPE("DOMAIN_COUPON_024", "%s không được null"),
    INVALID_COUPON_USAGE_ID("DOMAIN_COUPON_USAGE_001", "%s không được null"),
    INVALID_COUPON_USAGE_COUPON_ID("DOMAIN_COUPON_USAGE_002", "%s không được null"),
    INVALID_COUPON_USAGE_USER_ID("DOMAIN_COUPON_USAGE_003", "%s không được null"),
    INVALID_COUPON_USAGE_ORDER_ID("DOMAIN_COUPON_USAGE_004", "%s không được null"),
    INVALID_COUPON_USAGE_USED_AT("DOMAIN_COUPON_USAGE_005", "%s không được nằm trong tương lai"),

    INVALID_BOOK_ID("DOMAIN_BOOK_001", "%s không được null"),
    INVALID_BOOK_TITLE("DOMAIN_BOOK_002", "%s không được để trống"),
    INVALID_BOOK_PRICE("DOMAIN_BOOK_003", "%s không được âm"),
    INVALID_BOOK_STOCK_QUANTITY("DOMAIN_BOOK_004", "%s không được âm"),
    INVALID_BOOK_CATEGORY_ID("DOMAIN_BOOK_005", "%s không được null"),
    INVALID_BOOK_AUTHOR_ID("DOMAIN_BOOK_006", "%s không được null"),
    INVALID_BOOK_PUBLISHER_ID("DOMAIN_BOOK_007", "%s không được null"),
    INVALID_BOOK_CREATED_AT("DOMAIN_BOOK_008", "%s không được nằm trong tương lai"),
    INVALID_BOOK_UPDATED_AT("DOMAIN_BOOK_009", "%s không được nằm trong tương lai"),
    INVALID_BOOK_DELETED_AT("DOMAIN_BOOK_010", "%s không được nằm trong tương lai"),
    INVALID_BOOK_AUDIT_ORDER("DOMAIN_BOOK_011", "%s không được sớm hơn %s"),
    BOOK_ALREADY_DELETED("DOMAIN_BOOK_012", "book đã bi xóa"),
    BOOK_DATA_NOT_CHANGED("DOMAIN_BOOK_013", "dữ liệu book phải khác dữ liệu hiện tại"),
    INVALID_BOOK_STOCK_DECREASE_QUANTITY("DOMAIN_BOOK_014", "%s phải lớn hơn 0"),
    BOOK_STOCK_NOT_ENOUGH("DOMAIN_BOOK_015", "ton kho không du"),
    INVALID_BOOK_STOCK_INCREASE_QUANTITY("DOMAIN_BOOK_016", "%s phải lớn hơn 0"),
    INVALID_BOOK_IMAGES("DOMAIN_BOOK_017", "%s không được chứa phần tử null"),
    INVALID_BOOK_IMAGE_ID("DOMAIN_BOOK_018", "%s không được null"),
    INVALID_BOOK_IMAGE_BOOK_ID("DOMAIN_BOOK_019", "%s không được null"),
    INVALID_BOOK_IMAGE_URL("DOMAIN_BOOK_020", "%s không được để trống"),
    INVALID_BOOK_IMAGE_FILE_ASSET_ID("DOMAIN_BOOK_039", "%s không được null"),
    INVALID_BOOK_IMAGE_PRIMARY("DOMAIN_BOOK_021", "%s không được null"),
    INVALID_BOOK_IMAGE_SORT_ORDER("DOMAIN_BOOK_022", "%s không được âm"),
    INVALID_BOOK_IMAGE_ALT_TEXT("DOMAIN_BOOK_023", "%s không được để trống"),
    INVALID_BOOK_IMAGE_CREATED_AT("DOMAIN_BOOK_024", "%s không được nằm trong tương lai"),
    INVALID_BOOK_DETAIL_ID("DOMAIN_BOOK_025", "%s không được null"),
    INVALID_BOOK_DETAIL_BOOK_ID("DOMAIN_BOOK_026", "%s không được null"),
    INVALID_BOOK_DETAIL_PAGE_COUNT("DOMAIN_BOOK_027", "%s phải lớn hơn 0"),
    INVALID_BOOK_DETAIL_PUBLICATION_YEAR("DOMAIN_BOOK_028", "%s phải lớn hơn 0"),
    INVALID_BOOK_DETAIL_LANGUAGE("DOMAIN_BOOK_029", "%s không được để trống"),
    INVALID_BOOK_DETAIL_COVER_TYPE("DOMAIN_BOOK_030", "%s không được để trống"),
    INVALID_BOOK_DETAIL_DIMENSIONS("DOMAIN_BOOK_031", "%s không được để trống"),
    INVALID_BOOK_DETAIL_WEIGHT("DOMAIN_BOOK_032", "%s phải lớn hơn 0"),
    INVALID_BOOK_DETAIL_TRANSLATOR("DOMAIN_BOOK_033", "%s không được để trống"),
    INVALID_BOOK_DETAIL_EDITION("DOMAIN_BOOK_034", "%s không được để trống"),
    BOOK_IMAGE_BOOK_ID_MISMATCH("DOMAIN_BOOK_035", "book image phải thuoc ve book hiện tại"),
    BOOK_DETAIL_BOOK_ID_MISMATCH("DOMAIN_BOOK_036", "book detail phải thuoc ve book hiện tại"),
    BOOK_HAS_MULTIPLE_PRIMARY_IMAGES("DOMAIN_BOOK_037", "book chỉ được co toi đã 1 anh chinh"),
    INVALID_BOOK_ISBN("DOMAIN_BOOK_038", "%s không được để trống"),

    INVALID_DIGITAL_ASSET_ID("DOMAIN_DIGITAL_ASSET_001", "%s không được null"),
    INVALID_DIGITAL_ASSET_BOOK_ID("DOMAIN_DIGITAL_ASSET_002", "%s không được null"),
    INVALID_DIGITAL_ASSET_FORMAT("DOMAIN_DIGITAL_ASSET_003", "%s không được null"),
    INVALID_DIGITAL_ASSET_TITLE("DOMAIN_DIGITAL_ASSET_004", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_FILE_NAME("DOMAIN_DIGITAL_ASSET_005", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_STORAGE_KEY("DOMAIN_DIGITAL_ASSET_006", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_MIME_TYPE("DOMAIN_DIGITAL_ASSET_007", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_FILE_SIZE("DOMAIN_DIGITAL_ASSET_008", "%s không được âm"),
    INVALID_DIGITAL_ASSET_CHECKSUM("DOMAIN_DIGITAL_ASSET_009", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_SAMPLE_STORAGE_KEY("DOMAIN_DIGITAL_ASSET_010", "%s không được để trống"),
    INVALID_DIGITAL_ASSET_FILE_ASSET_ID("DOMAIN_DIGITAL_ASSET_017", "%s không được null"),
    INVALID_DIGITAL_ASSET_SAMPLE_FILE_ASSET_ID("DOMAIN_DIGITAL_ASSET_018", "%s không được hop le"),
    INVALID_DIGITAL_ASSET_PRICE("DOMAIN_DIGITAL_ASSET_011", "%s không được âm"),
    INVALID_DIGITAL_ASSET_CREATED_AT("DOMAIN_DIGITAL_ASSET_012", "%s không được nằm trong tương lai"),
    INVALID_DIGITAL_ASSET_UPDATED_AT("DOMAIN_DIGITAL_ASSET_013", "%s không được nằm trong tương lai"),
    INVALID_DIGITAL_ASSET_DELETED_AT("DOMAIN_DIGITAL_ASSET_014", "%s không được nằm trong tương lai"),
    INVALID_DIGITAL_ASSET_AUDIT_ORDER("DOMAIN_DIGITAL_ASSET_015", "%s không được sớm hơn %s"),
    DIGITAL_ASSET_ALREADY_DELETED("DOMAIN_DIGITAL_ASSET_016", "tài nguyên số đã bi xóa"),

    INVALID_USER_DIGITAL_ACCESS_ID("DOMAIN_USER_DIGITAL_ACCESS_001", "%s không được null"),
    INVALID_USER_DIGITAL_ACCESS_USER_ID("DOMAIN_USER_DIGITAL_ACCESS_002", "%s không được null"),
    INVALID_USER_DIGITAL_ACCESS_DIGITAL_ASSET_ID("DOMAIN_USER_DIGITAL_ACCESS_003", "%s không được null"),
    INVALID_USER_DIGITAL_ACCESS_TYPE("DOMAIN_USER_DIGITAL_ACCESS_004", "%s không được null"),
    INVALID_USER_DIGITAL_ACCESS_STATUS("DOMAIN_USER_DIGITAL_ACCESS_005", "%s không được null"),
    INVALID_USER_DIGITAL_ACCESS_EXPIRES_AT("DOMAIN_USER_DIGITAL_ACCESS_006", "%s không hợp lệ"),
    INVALID_USER_DIGITAL_ACCESS_CREATED_AT("DOMAIN_USER_DIGITAL_ACCESS_007", "%s không được nằm trong tương lai"),
    INVALID_USER_DIGITAL_ACCESS_UPDATED_AT("DOMAIN_USER_DIGITAL_ACCESS_008", "%s không được nằm trong tương lai"),
    INVALID_USER_DIGITAL_ACCESS_DELETED_AT("DOMAIN_USER_DIGITAL_ACCESS_009", "%s không được nằm trong tương lai"),
    INVALID_USER_DIGITAL_ACCESS_AUDIT_ORDER("DOMAIN_USER_DIGITAL_ACCESS_010", "%s không được sớm hơn %s"),
    USER_DIGITAL_ACCESS_ALREADY_DELETED("DOMAIN_USER_DIGITAL_ACCESS_011", "quyền truy cập sách so đã bi xóa"),

    INVALID_READING_PROGRESS_ID("DOMAIN_READING_PROGRESS_001", "%s không được null"),
    INVALID_READING_PROGRESS_USER_ID("DOMAIN_READING_PROGRESS_002", "%s không được null"),
    INVALID_READING_PROGRESS_DIGITAL_ASSET_ID("DOMAIN_READING_PROGRESS_003", "%s không được null"),
    INVALID_READING_PROGRESS_CURRENT_PAGE("DOMAIN_READING_PROGRESS_004", "%s không được âm"),
    INVALID_READING_PROGRESS_PERCENT("DOMAIN_READING_PROGRESS_005", "%s phải tu 0 den 100"),
    INVALID_READING_PROGRESS_POSITION_DATA("DOMAIN_READING_PROGRESS_006", "%s không được để trống"),
    INVALID_READING_PROGRESS_LAST_READ_AT("DOMAIN_READING_PROGRESS_007", "%s không được nằm trong tương lai"),
    INVALID_READING_PROGRESS_CREATED_AT("DOMAIN_READING_PROGRESS_008", "%s không được nằm trong tương lai"),
    INVALID_READING_PROGRESS_UPDATED_AT("DOMAIN_READING_PROGRESS_009", "%s không được nằm trong tương lai"),
    INVALID_READING_PROGRESS_AUDIT_ORDER("DOMAIN_READING_PROGRESS_010", "%s không được sớm hơn %s"),

    INVALID_IMPORT_RECEIPT_ID("DOMAIN_IMPORT_RECEIPT_001", "%s không được null"),
    INVALID_IMPORT_RECEIPT_SUPPLIER_ID("DOMAIN_IMPORT_RECEIPT_002", "%s không được null"),
    INVALID_IMPORT_RECEIPT_ITEMS("DOMAIN_IMPORT_RECEIPT_003", "%s không được chứa phần tử null"),
    INVALID_IMPORT_RECEIPT_TOTAL_AMOUNT("DOMAIN_IMPORT_RECEIPT_004", "%s không được âm"),
    INVALID_IMPORT_RECEIPT_NOTE("DOMAIN_IMPORT_RECEIPT_005", "%s không được để trống"),
    INVALID_IMPORT_RECEIPT_CREATED_AT("DOMAIN_IMPORT_RECEIPT_006", "%s không được nằm trong tương lai"),
    INVALID_IMPORT_RECEIPT_UPDATED_AT("DOMAIN_IMPORT_RECEIPT_007", "%s không được nằm trong tương lai"),
    INVALID_IMPORT_RECEIPT_CREATED_BY("DOMAIN_IMPORT_RECEIPT_008", "%s không được null"),
    INVALID_IMPORT_RECEIPT_AUDIT_ORDER("DOMAIN_IMPORT_RECEIPT_009", "%s không được sớm hơn %s"),
    IMPORT_RECEIPT_MUST_HAVE_AT_LEAST_ONE_ITEM("DOMAIN_IMPORT_RECEIPT_010", "phiếu nhập phải co it nhat 1 item"),
    IMPORT_RECEIPT_TOTAL_AMOUNT_MISMATCH("DOMAIN_IMPORT_RECEIPT_011", "tong tien phiếu nhập không khớp voi danh sách item"),
    INVALID_IMPORT_RECEIPT_ITEM_ID("DOMAIN_IMPORT_RECEIPT_012", "%s không được null"),
    INVALID_IMPORT_RECEIPT_ITEM_BOOK_ID("DOMAIN_IMPORT_RECEIPT_013", "%s không được null"),
    INVALID_IMPORT_RECEIPT_ITEM_BOOK_TITLE("DOMAIN_IMPORT_RECEIPT_014", "%s không được để trống"),
    INVALID_IMPORT_RECEIPT_ITEM_UNIT_COST("DOMAIN_IMPORT_RECEIPT_015", "%s không được âm"),
    INVALID_IMPORT_RECEIPT_ITEM_QUANTITY("DOMAIN_IMPORT_RECEIPT_016", "%s phải lớn hơn 0"),
    INVALID_IMPORT_RECEIPT_ITEM_LINE_TOTAL("DOMAIN_IMPORT_RECEIPT_017", "%s không được âm"),
    IMPORT_RECEIPT_ITEM_LINE_TOTAL_MISMATCH("DOMAIN_IMPORT_RECEIPT_018", "tong tien item phiếu nhập không khớp don gia va số lượng"),

    INVALID_CART_ID("DOMAIN_CART_001", "%s không được null"),
    INVALID_CART_USER_ID("DOMAIN_CART_002", "%s không được null"),
    INVALID_CART_ITEMS("DOMAIN_CART_003", "%s không được chứa phần tử null"),
    INVALID_CART_CREATED_AT("DOMAIN_CART_004", "%s không được nằm trong tương lai"),
    INVALID_CART_UPDATED_AT("DOMAIN_CART_005", "%s không được nằm trong tương lai"),
    INVALID_CART_AUDIT_ORDER("DOMAIN_CART_006", "%s không được sớm hơn %s"),
    INVALID_CART_ITEM_ID("DOMAIN_CART_007", "%s không được null"),
    INVALID_CART_ITEM_BOOK_ID("DOMAIN_CART_008", "%s không được null"),
    INVALID_CART_ITEM_QUANTITY("DOMAIN_CART_009", "%s phải lớn hơn 0"),
    INVALID_CART_ITEM_CREATED_AT("DOMAIN_CART_010", "%s không được nằm trong tương lai"),
    INVALID_CART_ITEM_UPDATED_AT("DOMAIN_CART_011", "%s không được nằm trong tương lai"),
    INVALID_CART_ITEM_AUDIT_ORDER("DOMAIN_CART_012", "%s không được sớm hơn %s"),
    CART_ITEM_NOT_FOUND("DOMAIN_CART_013", "không tìm thấy sách trong giỏ hàng"),
    CART_ITEM_QUANTITY_EXCEEDS_STOCK("DOMAIN_CART_014", "số lượng vượt quá ton kho"),
    INVALID_CART_ITEM_TYPE("DOMAIN_CART_015", "%s không được null"),
    INVALID_CART_ITEM_DIGITAL_ASSET_ID("DOMAIN_CART_016", "%s không được null"),

    INVALID_ORDER_ID("DOMAIN_ORDER_001", "%s không được null"),
    INVALID_ORDER_USER_ID("DOMAIN_ORDER_002", "%s không được null"),
    INVALID_ORDER_ITEMS("DOMAIN_ORDER_003", "%s không được chứa phần tử null"),
    INVALID_ORDER_TOTAL_AMOUNT("DOMAIN_ORDER_004", "%s không được âm"),
    INVALID_ORDER_DISCOUNT_AMOUNT("DOMAIN_ORDER_005", "%s không được âm"),
    INVALID_ORDER_SHIPPING_FEE("DOMAIN_ORDER_006", "%s không được âm"),
    INVALID_ORDER_FINAL_AMOUNT("DOMAIN_ORDER_007", "%s không được âm"),
    INVALID_ORDER_COUPON_CODE("DOMAIN_ORDER_008", "%s không được để trống"),
    INVALID_ORDER_PAYMENT_METHOD("DOMAIN_ORDER_009", "%s không được null"),
    INVALID_ORDER_PAYMENT_STATUS("DOMAIN_ORDER_010", "%s không được null"),
    INVALID_ORDER_STATUS("DOMAIN_ORDER_011", "%s không được null"),
    INVALID_ORDER_RECEIVER_NAME("DOMAIN_ORDER_012", "%s không được để trống"),
    INVALID_ORDER_RECEIVER_PHONE("DOMAIN_ORDER_013", "%s phải có đúng 10 chữ số và bắt đầu bằng 0"),
    INVALID_ORDER_RECEIVER_ADDRESS("DOMAIN_ORDER_014", "%s không được để trống"),
    INVALID_ORDER_CREATED_AT("DOMAIN_ORDER_015", "%s không được nằm trong tương lai"),
    INVALID_ORDER_UPDATED_AT("DOMAIN_ORDER_016", "%s không được nằm trong tương lai"),
    INVALID_ORDER_CANCELLED_AT("DOMAIN_ORDER_017", "%s không được nằm trong tương lai"),
    INVALID_ORDER_AUDIT_ORDER("DOMAIN_ORDER_018", "%s không được sớm hơn %s"),
    ORDER_MUST_HAVE_AT_LEAST_ONE_ITEM("DOMAIN_ORDER_019", "order phải co it nhat 1 item"),
    ORDER_TOTAL_AMOUNT_MISMATCH("DOMAIN_ORDER_020", "tong tien order không khớp voi danh sách item"),
    ORDER_FINAL_AMOUNT_MISMATCH("DOMAIN_ORDER_021", "so tien cuoi cung không khớp tong tien, giảm giá va phi ship"),
    DELIVERED_ORDER_CANNOT_BE_CANCELLED("DOMAIN_ORDER_022", "đơn hàng đã giao không thể huy"),
    CANCELLED_ORDER_CANNOT_BE_UPDATED("DOMAIN_ORDER_023", "đơn hàng đã huy không thể cập nhật"),
    INVALID_ORDER_STATUS_TRANSITION("DOMAIN_ORDER_024", "không thể chuyen trang thai tu %s sang %s"),
    ORDER_STATUS_NOT_CHANGED("DOMAIN_ORDER_025", "trang thai order phải khác trang thai hiện tại"),
    INVALID_ORDER_ITEM_ID("DOMAIN_ORDER_026", "%s không được null"),
    INVALID_ORDER_ITEM_BOOK_ID("DOMAIN_ORDER_027", "%s không được null"),
    INVALID_ORDER_ITEM_BOOK_TITLE("DOMAIN_ORDER_028", "%s không được để trống"),
    INVALID_ORDER_ITEM_UNIT_PRICE("DOMAIN_ORDER_029", "%s không được âm"),
    INVALID_ORDER_ITEM_QUANTITY("DOMAIN_ORDER_030", "%s phải lớn hơn 0"),
    INVALID_ORDER_ITEM_LINE_TOTAL("DOMAIN_ORDER_031", "%s không được âm"),
    ORDER_ITEM_LINE_TOTAL_MISMATCH("DOMAIN_ORDER_032", "tong tien item không khớp don gia va số lượng"),
    INVALID_ORDER_ORDER_CODE("DOMAIN_ORDER_033", "%s không được để trống"),
    INVALID_ORDER_PRODUCT_TOTAL("DOMAIN_ORDER_034", "%s không được âm"),
    INVALID_ORDER_SHIPPING_DISCOUNT("DOMAIN_ORDER_035", "%s không được âm"),
    INVALID_ORDER_COUPON_DISCOUNT("DOMAIN_ORDER_036", "%s không được âm"),
    ORDER_PAYMENT_TOTAL_MISMATCH("DOMAIN_ORDER_037", "tong tien thanh toán không khớp tạm tính, phi ship va giảm giá"),
    INVALID_ORDER_ITEM_TYPE("DOMAIN_ORDER_038", "%s không được null"),
    INVALID_ORDER_ITEM_DIGITAL_ASSET_ID("DOMAIN_ORDER_039", "%s không được null"),

    INVALID_SHIPMENT_ID("DOMAIN_SHIPMENT_001", "%s không được null"),
    INVALID_SHIPMENT_ORDER_ID("DOMAIN_SHIPMENT_002", "%s không được null"),
    INVALID_SHIPMENT_SHIPPER_ID("DOMAIN_SHIPMENT_003", "%s không được null"),
    INVALID_SHIPMENT_STATUS("DOMAIN_SHIPMENT_004", "%s không được null"),
    INVALID_SHIPMENT_FAILURE_REASON("DOMAIN_SHIPMENT_005", "%s không hợp lệ"),
    INVALID_SHIPMENT_ASSIGNED_AT("DOMAIN_SHIPMENT_006", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_UPDATED_AT("DOMAIN_SHIPMENT_007", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_PICKED_UP_AT("DOMAIN_SHIPMENT_008", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_DELIVERING_AT("DOMAIN_SHIPMENT_009", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_DELIVERED_AT("DOMAIN_SHIPMENT_010", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_FAILED_AT("DOMAIN_SHIPMENT_011", "%s không được nằm trong tương lai"),
    INVALID_SHIPMENT_AUDIT_ORDER("DOMAIN_SHIPMENT_012", "%s không được sớm hơn %s"),
    INVALID_SHIPMENT_STATUS_TIMELINE("DOMAIN_SHIPMENT_013", "moc thoi gian shipment không hợp lệ voi trang thai hiện tại"),
    INVALID_SHIPMENT_STATUS_TRANSITION("DOMAIN_SHIPMENT_014", "không thể chuyen trang thai shipment tu %s sang %s"),
    SHIPMENT_STATUS_NOT_CHANGED("DOMAIN_SHIPMENT_015", "trang thai shipment phải khác trang thai hiện tại"),

    INVALID_PAYMENT_ID("DOMAIN_PAYMENT_001", "%s không được null"),
    INVALID_PAYMENT_ORDER_ID("DOMAIN_PAYMENT_002", "%s không được null"),
    INVALID_PAYMENT_PROVIDER("DOMAIN_PAYMENT_003", "%s không được null"),
    INVALID_PAYMENT_STATUS("DOMAIN_PAYMENT_004", "%s không được null"),
    INVALID_PAYMENT_AMOUNT("DOMAIN_PAYMENT_005", "%s không được âm"),
    INVALID_PAYMENT_MERCHANT_ID("DOMAIN_PAYMENT_006", "%s không được để trống"),
    INVALID_PAYMENT_TRANSACTION_ID("DOMAIN_PAYMENT_007", "%s không được để trống"),
    INVALID_PAYMENT_REFERENCE_CODE("DOMAIN_PAYMENT_008", "%s không được để trống"),
    INVALID_PAYMENT_TRANSFER_CONTENT("DOMAIN_PAYMENT_009", "%s không được để trống"),
    INVALID_PAYMENT_GATEWAY("DOMAIN_PAYMENT_010", "%s không được để trống"),
    INVALID_PAYMENT_PAID_AT("DOMAIN_PAYMENT_011", "%s không được nằm trong tương lai"),
    INVALID_PAYMENT_CREATED_AT("DOMAIN_PAYMENT_012", "%s không được nằm trong tương lai"),
    INVALID_PAYMENT_UPDATED_AT("DOMAIN_PAYMENT_013", "%s không được nằm trong tương lai"),
    INVALID_PAYMENT_AUDIT_ORDER("DOMAIN_PAYMENT_014", "%s không được sớm hơn %s"),

    INVALID_ROLE_ID("DOMAIN_ROLE_001", "%s không được null"),
    INVALID_ROLE_NAME("DOMAIN_ROLE_002", "%s không được null"),
    INVALID_ROLE_DESCRIPTION("DOMAIN_ROLE_003", "%s không được để trống"),
    INVALID_ROLE_PERMISSIONS("DOMAIN_ROLE_004", "%s không được chứa phần tử null"),
    INVALID_ROLE_CREATED_AT("DOMAIN_ROLE_005", "%s không được nằm trong tương lai"),
    INVALID_ROLE_UPDATED_AT("DOMAIN_ROLE_006", "%s không được nằm trong tương lai"),
    INVALID_ROLE_DELETED_AT("DOMAIN_ROLE_007", "%s không được nằm trong tương lai"),
    INVALID_ROLE_AUDIT_ORDER("DOMAIN_ROLE_008", "%s không được sớm hơn %s"),
    ROLE_ALREADY_DELETED("DOMAIN_ROLE_009", "role đã bi xóa"),
    ROLE_DATA_NOT_CHANGED("DOMAIN_ROLE_010", "dữ liệu role phải khác dữ liệu hiện tại"),

    INVALID_PERMISSION_ID("DOMAIN_PERMISSION_001", "%s không được null"),
    INVALID_PERMISSION_CODE("DOMAIN_PERMISSION_002", "%s không được null"),
    INVALID_PERMISSION_DESCRIPTION("DOMAIN_PERMISSION_003", "%s không được để trống"),
    INVALID_PERMISSION_CREATED_AT("DOMAIN_PERMISSION_004", "%s không được nằm trong tương lai"),
    INVALID_PERMISSION_UPDATED_AT("DOMAIN_PERMISSION_005", "%s không được nằm trong tương lai"),
    INVALID_PERMISSION_DELETED_AT("DOMAIN_PERMISSION_006", "%s không được nằm trong tương lai"),
    INVALID_PERMISSION_AUDIT_ORDER("DOMAIN_PERMISSION_007", "%s không được sớm hơn %s"),
    PERMISSION_ALREADY_DELETED("DOMAIN_PERMISSION_008", "permission đã bi xóa"),
    PERMISSION_CODE_NOT_CHANGED("DOMAIN_PERMISSION_009", "code permission phải khác code hiện tại"),
    PERMISSION_DATA_NOT_CHANGED("DOMAIN_PERMISSION_010", "dữ liệu permission phải khác dữ liệu hiện tại"),

    INVALID_REFRESH_TOKEN_ID("DOMAIN_REFRESH_TOKEN_001", "%s không được null"),
    INVALID_REFRESH_TOKEN_USER_ID("DOMAIN_REFRESH_TOKEN_002", "%s không được null"),
    INVALID_REFRESH_TOKEN_TOKEN("DOMAIN_REFRESH_TOKEN_003", "%s không được để trống"),
    INVALID_REFRESH_TOKEN_EXPIRES_AT("DOMAIN_REFRESH_TOKEN_004", "%s phải nam trong tương lai"),
    INVALID_REFRESH_TOKEN_CREATED_AT("DOMAIN_REFRESH_TOKEN_005", "%s không được nằm trong tương lai"),
    INVALID_REFRESH_TOKEN_AUDIT_ORDER("DOMAIN_REFRESH_TOKEN_006", "%s phải sau %s"),

    INVALID_FILE_ASSET_ID("DOMAIN_FILE_ASSET_001", "%s không được null"),
    INVALID_FILE_ASSET_PROVIDER("DOMAIN_FILE_ASSET_002", "%s không được null"),
    INVALID_FILE_ASSET_PURPOSE("DOMAIN_FILE_ASSET_003", "%s không được null"),
    INVALID_FILE_ASSET_BUCKET("DOMAIN_FILE_ASSET_004", "%s không được để trống"),
    INVALID_FILE_ASSET_STORAGE_KEY("DOMAIN_FILE_ASSET_005", "%s không được để trống"),
    INVALID_FILE_ASSET_PUBLIC_URL("DOMAIN_FILE_ASSET_006", "%s không được để trống"),
    INVALID_FILE_ASSET_ORIGINAL_NAME("DOMAIN_FILE_ASSET_007", "%s không được để trống"),
    INVALID_FILE_ASSET_CONTENT_TYPE("DOMAIN_FILE_ASSET_008", "%s không được để trống"),
    INVALID_FILE_ASSET_SIZE_BYTES("DOMAIN_FILE_ASSET_009", "%s không được âm"),
    INVALID_FILE_ASSET_CHECKSUM_SHA256("DOMAIN_FILE_ASSET_010", "%s không được để trống"),
    INVALID_FILE_ASSET_VISIBILITY("DOMAIN_FILE_ASSET_011", "%s không được null"),
    INVALID_FILE_ASSET_STATUS("DOMAIN_FILE_ASSET_012", "%s không được null"),
    INVALID_FILE_ASSET_CREATED_BY("DOMAIN_FILE_ASSET_013", "%s không được null"),
    INVALID_FILE_ASSET_CREATED_AT("DOMAIN_FILE_ASSET_014", "%s không được nằm trong tương lai"),
    INVALID_FILE_ASSET_UPDATED_AT("DOMAIN_FILE_ASSET_015", "%s không được nằm trong tương lai"),
    INVALID_FILE_ASSET_DELETED_AT("DOMAIN_FILE_ASSET_016", "%s không được nằm trong tương lai"),
    INVALID_FILE_ASSET_AUDIT_ORDER("DOMAIN_FILE_ASSET_017", "%s không được sớm hơn %s"),
    FILE_ASSET_ALREADY_DELETED("DOMAIN_FILE_ASSET_018", "file asset đã bi xóa"),

    INVALID_PASSWORD_RESET_TOKEN_ID("DOMAIN_PASSWORD_RESET_TOKEN_001", "%s không được null"),
    INVALID_PASSWORD_RESET_TOKEN_USER_ID("DOMAIN_PASSWORD_RESET_TOKEN_002", "%s không được null"),
    INVALID_PASSWORD_RESET_TOKEN_HASH("DOMAIN_PASSWORD_RESET_TOKEN_003", "%s không được để trống"),
    INVALID_PASSWORD_RESET_TOKEN_EXPIRES_AT("DOMAIN_PASSWORD_RESET_TOKEN_004", "%s không được null"),
    INVALID_PASSWORD_RESET_TOKEN_USED_AT("DOMAIN_PASSWORD_RESET_TOKEN_005", "%s không được nằm trong tương lai"),
    INVALID_PASSWORD_RESET_TOKEN_CREATED_AT("DOMAIN_PASSWORD_RESET_TOKEN_006", "%s không được nằm trong tương lai"),
    INVALID_PASSWORD_RESET_TOKEN_AUDIT_ORDER("DOMAIN_PASSWORD_RESET_TOKEN_007", "%s không được sớm hơn %s"),

    INVALID_REVIEW_ID("DOMAIN_REVIEW_001", "%s không được null"),
    INVALID_REVIEW_USER_ID("DOMAIN_REVIEW_002", "%s không được null"),
    INVALID_REVIEW_BOOK_ID("DOMAIN_REVIEW_003", "%s không được null"),
    INVALID_REVIEW_ORDER_ITEM_ID("DOMAIN_REVIEW_004", "%s không được null"),
    INVALID_REVIEW_RATING("DOMAIN_REVIEW_005", "%s phải tu 1 den 5"),
    INVALID_REVIEW_COMMENT("DOMAIN_REVIEW_006", "%s không được vượt quá 1000 ký tự"),
    INVALID_REVIEW_CREATED_AT("DOMAIN_REVIEW_007", "%s không được nằm trong tương lai"),
    INVALID_REVIEW_UPDATED_AT("DOMAIN_REVIEW_008", "%s không được nằm trong tương lai"),
    INVALID_REVIEW_DELETED_AT("DOMAIN_REVIEW_009", "%s không được nằm trong tương lai"),
    INVALID_REVIEW_AUDIT_ORDER("DOMAIN_REVIEW_010", "%s không được sớm hơn %s"),
    REVIEW_ALREADY_DELETED("DOMAIN_REVIEW_011", "review đã bi xóa"),
    DELETED_REVIEW_CANNOT_UPDATE("DOMAIN_REVIEW_012", "review đã xóa không thể cập nhật"),

    INVALID_STOCK_MOVEMENT_ID("DOMAIN_STOCK_MOVEMENT_001", "%s không được null"),
    INVALID_STOCK_MOVEMENT_BOOK_ID("DOMAIN_STOCK_MOVEMENT_002", "%s không được null"),
    INVALID_STOCK_MOVEMENT_TYPE("DOMAIN_STOCK_MOVEMENT_003", "%s không được null"),
    INVALID_STOCK_MOVEMENT_QUANTITY("DOMAIN_STOCK_MOVEMENT_004", "%s phải lớn hơn 0"),
    INVALID_STOCK_MOVEMENT_BEFORE_QUANTITY("DOMAIN_STOCK_MOVEMENT_005", "%s không được âm"),
    INVALID_STOCK_MOVEMENT_AFTER_QUANTITY("DOMAIN_STOCK_MOVEMENT_006", "%s không được âm"),
    INVALID_STOCK_MOVEMENT_REFERENCE_TYPE("DOMAIN_STOCK_MOVEMENT_007", "%s không được để trống"),
    INVALID_STOCK_MOVEMENT_NOTE("DOMAIN_STOCK_MOVEMENT_008", "%s không được để trống"),
    INVALID_STOCK_MOVEMENT_CREATED_AT("DOMAIN_STOCK_MOVEMENT_009", "%s không được nằm trong tương lai"),
    INVALID_STOCK_MOVEMENT_CREATED_BY("DOMAIN_STOCK_MOVEMENT_010", "%s không được null"),
    STOCK_MOVEMENT_QUANTITY_MISMATCH("DOMAIN_STOCK_MOVEMENT_011", "so luong bien dong khong khop ton truoc va sau"),

    INVALID_WISHLIST_ITEM_ID("DOMAIN_WISHLIST_001", "%s khong duoc null"),
    INVALID_WISHLIST_ITEM_USER_ID("DOMAIN_WISHLIST_002", "%s khong duoc null"),
    INVALID_WISHLIST_ITEM_BOOK_ID("DOMAIN_WISHLIST_003", "%s khong duoc null"),
    INVALID_WISHLIST_ITEM_CREATED_AT("DOMAIN_WISHLIST_004", "%s khong duoc nam trong tuong lai"),
    INVALID_WISHLIST_ITEM_UPDATED_AT("DOMAIN_WISHLIST_005", "%s khong duoc nam trong tuong lai"),
    INVALID_WISHLIST_ITEM_DELETED_AT("DOMAIN_WISHLIST_006", "%s khong duoc nam trong tuong lai"),
    INVALID_WISHLIST_ITEM_AUDIT_ORDER("DOMAIN_WISHLIST_007", "%s khong duoc som hon %s"),
    WISHLIST_ITEM_ALREADY_DELETED("DOMAIN_WISHLIST_008", "wishlist item da bi xoa"),
    WISHLIST_ITEM_ALREADY_ACTIVE("DOMAIN_WISHLIST_009", "wishlist item dang hoat dong");

    private final String code;
    private final String messageTemplate;

    DomainErrorCode(String code, String messageTemplate) {
        this.code = code;
        this.messageTemplate = messageTemplate;
    }

    public String getCode() {
        return code;
    }

    public String message(Object... args) {
        return String.format(messageTemplate, args);
    }
}

